export type BattleSkills = 'attack-1' |
    'attack-2' |
    'attack-3' |
    'polar-hunter' |
    'tropic-hunter' |
    'element' |
    'fire-attack-1' |
    'fire-attack-2' |
    'ice-attack-1' |
    'ice-attack-2' |
    'thunder-attack-1' |
    'thunder-attack-2' |
    'dragon-attack-1' |
    'dragon-attack-2' |
    'water-attack-1' |
    'water-attack-2' |
    'status-1' |
    'status-2' |
    'sharp-1' |
    'sharp-2' |
    'razor-sharp' |
    'bludgeoner' |
    'crit-draw' |
    'load-up' |
    'affinity-1' |
    'affinity-2' |
    'affinity-3' |
    'weakness-exploit' |
    'repeat-offender' |
    'status-crit' |
    'elemental-crit' |
    'crit-boost' |
    'bitter-affinity' |
    'artillery-1' |
    'artillery-2' |
    'latent-power-1' |
    'latent-power-2' |
    'challenger-1' |
    'challenger-2' |
    'peak-performance' |
    'trump-card' |
    'dragonheart' |
    'adrenaline-2' |
    'fortify' |
    'resentment' |
    'resuscitate' |
    'airborne';
